# Generated by Django 5.1.3 on 2024-11-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Category',
            new_name='category',
        ),
    ]
